//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTROLBPA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<!--\r\n /* Font Definitions */\r\n @font-face\r\n\t{font-family:\"MS Mincho\";\r\n\tpanose-1" +
            ":2 2 6 9 4 2 5 8 3 4;}\r\n@font-face\r\n\t{font-family:\"Cambria Math\";\r\n\tpanose-1:2 4" +
            " 5 3 5 4 6 3 2 4;}\r\n@font-face\r\n\t{font-family:\"Calibri Light\";\r\n\tpanose-1:2 15 3" +
            " 2 2 2 4 3 2 4;}\r\n@font-face\r\n\t{font-family:Calibri;\r\n\tpanose-1:2 15 5 2 2 2 4 3" +
            " 2 4;}\r\n@font-face\r\n\t{font-family:\"\\@MS Mincho\";\r\n\tpanose-1:2 2 6 9 4 2 5 8 3 4;" +
            "}\r\n /* Style Definitions */\r\n p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n\t{margin" +
            "-top:0in;\r\n\tmargin-right:0in;\r\n\tmargin-bottom:8.0pt;\r\n\tmargin-left:0in;\r\n\tline-h" +
            "eight:107%;\r\n\tfont-size:11.0pt;\r\n\tfont-family:\"Calibri\",sans-serif;}\r\nh1\r\n\t{mso-" +
            "style-link:\"Heading 1 Char\";\r\n\tmargin-top:12.0pt;\r\n\tmargin-right:0in;\r\n\tmargin-b" +
            "ottom:0in;\r\n\tmargin-left:0in;\r\n\tmargin-bottom:.0001pt;\r\n\tline-height:107%;\r\n\tpag" +
            "e-break-after:avoid;\r\n\tfont-size:16.0pt;\r\n\tfont-family:\"Calibri Light\",sans-seri" +
            "f;\r\n\tcolor:#2E74B5;\r\n\tfont-weight:normal;}\r\nh2\r\n\t{mso-style-link:\"Heading 2 Char" +
            "\";\r\n\tmargin-top:2.0pt;\r\n\tmargin-right:0in;\r\n\tmargin-bottom:0in;\r\n\tmargin-left:0i" +
            "n;\r\n\tmargin-bottom:.0001pt;\r\n\tline-height:107%;\r\n\tpage-break-after:avoid;\r\n\tfont" +
            "-size:13.0pt;\r\n\tfont-family:\"Calibri Light\",sans-serif;\r\n\tcolor:#2E74B5;\r\n\tfont-" +
            "weight:normal;}\r\na:link, span.MsoHyperlink\r\n\t{color:#0563C1;\r\n\ttext-decoration:u" +
            "nderline;}\r\na:visited, span.MsoHyperlinkFollowed\r\n\t{color:#954F72;\r\n\ttext-decora" +
            "tion:underline;}\r\nspan.Heading1Char\r\n\t{mso-style-name:\"Heading 1 Char\";\r\n\tmso-st" +
            "yle-link:\"Heading 1\";\r\n\tfont-family:\"Calibri Light\",sans-serif;\r\n\tcolor:#2E74B5;" +
            "}\r\nspan.Heading2Char\r\n\t{mso-style-name:\"Heading 2 Char\";\r\n\tmso-style-link:\"Headi" +
            "ng 2\";\r\n\tfont-family:\"Calibri Light\",sans-serif;\r\n\tcolor:#2E74B5;}\r\np.msonormal0" +
            ", li.msonormal0, div.msonormal0\r\n\t{mso-style-name:msonormal;\r\n\tmargin-right:0in;" +
            "\r\n\tmargin-left:0in;\r\n\tfont-size:12.0pt;\r\n\tfont-family:\"Times New Roman\",serif;}\r" +
            "\n.MsoChpDefault\r\n\t{font-family:\"Calibri\",sans-serif;}\r\n.MsoPapDefault\r\n\t{margin-" +
            "bottom:8.0pt;\r\n\tline-height:107%;}\r\n@page WordSection1\r\n\t{size:8.5in 11.0in;\r\n\tm" +
            "argin:1.0in 1.0in 1.0in 1.0in;}\r\ndiv.WordSection1\r\n\t{page:WordSection1;}\r\n-->")]
        public string htmlStyle {
            get {
                return ((string)(this["htmlStyle"]));
            }
        }
    }
}
